import itertools
from wargame.models.agent_response import AgentResponse, ActionType
from wargame.providers.base import BaseLLMProvider

MOCK_RESPONSES: dict[str, list[AgentResponse]] = {
    "developer": [
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Implemented API Gateway configuration on Azure APIM with routing rules.",
                      referenced_stories=["HU-001"], confidence=0.9, tech_debt_added=0),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Code review passed, PR ready for merge. All unit tests green.",
                      referenced_stories=["HU-002"], confidence=0.85, tech_debt_added=0),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Waiting for QA sign-off on HU-003 before proceeding.",
                      referenced_stories=["HU-003"], confidence=0.7, tech_debt_added=0),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Legacy Oracle stored procedure is undocumented; need Tech Lead input.",
                      referenced_stories=["HU-011"], confidence=0.6, tech_debt_added=3),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Completed schema migration script for EPIC-02 with rollback support.",
                      referenced_stories=["HU-021"], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Reviewed PR for service mesh integration. Logic is sound, merging.",
                      referenced_stories=["HU-022"], confidence=0.83, tech_debt_added=0),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Blocked on infrastructure provisioning. No action possible this turn.",
                      referenced_stories=[], confidence=0.65, tech_debt_added=0),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Spring Boot microservice scaffold complete with Actuator and Prometheus endpoints.",
                      referenced_stories=["HU-002"], confidence=0.91, tech_debt_added=0),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Feature branch reviewed — no regressions detected in contract tests.",
                      referenced_stories=["HU-011"], confidence=0.86, tech_debt_added=0),
        AgentResponse(agent_id="developer", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="PL/SQL conversion ambiguity in HU-022; requesting architecture decision.",
                      referenced_stories=["HU-022"], confidence=0.58, tech_debt_added=2),
    ],
    "dev_agent_senior": [
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Implemented API Gateway routing rules and APIM policies for HU-001.",
                      referenced_stories=["HU-001"], confidence=0.92, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="PR reviewed and approved — unit tests green, no regressions.",
                      referenced_stories=["HU-002"], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Awaiting QA sign-off on previous story before picking up next.",
                      referenced_stories=["HU-011"], confidence=0.72, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Undocumented Oracle PL/SQL dependency found — escalating to Tech Lead.",
                      referenced_stories=["HU-011"], confidence=0.61, tech_debt_added=3),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Schema migration script with rollback support delivered for HU-021.",
                      referenced_stories=["HU-021"], confidence=0.89, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Service mesh PR reviewed — resilience patterns correctly applied.",
                      referenced_stories=["HU-022"], confidence=0.84, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Waiting for infrastructure provisioning before continuing.",
                      referenced_stories=[], confidence=0.68, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Spring Boot microservice scaffold with Actuator and Prometheus done.",
                      referenced_stories=["HU-002"], confidence=0.93, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Contract tests pass — feature branch merged to main.",
                      referenced_stories=["HU-001"], confidence=0.87, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_senior", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="PL/SQL ambiguity in HU-022 requires architecture decision before proceeding.",
                      referenced_stories=["HU-022"], confidence=0.59, tech_debt_added=2),
    ],
    "dev_agent_junior": [
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Implemented basic CRUD endpoints for customer portal stories.",
                      referenced_stories=["HU-002"], confidence=0.78, tech_debt_added=2),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Reviewed PR for test utilities — logic looks correct to me.",
                      referenced_stories=["HU-001"], confidence=0.72, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Not sure how to proceed with Oracle stored procedure migration. Waiting for guidance.",
                      referenced_stories=["HU-011"], confidence=0.55, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Azure Kubernetes manifest syntax unclear — asking senior developer for help.",
                      referenced_stories=["HU-021"], confidence=0.5, tech_debt_added=1),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Pair programming session needed — blocked on integration test setup.",
                      referenced_stories=["HU-022"], confidence=0.52, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="PR for utility helpers reviewed — straightforward changes approved.",
                      referenced_stories=["HU-002"], confidence=0.74, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Unit tests written for migration helper functions. All passing.",
                      referenced_stories=["HU-011"], confidence=0.8, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Reviewing documentation before starting next story to avoid mistakes.",
                      referenced_stories=[], confidence=0.6, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Code change for config loading reviewed — no issues found.",
                      referenced_stories=["HU-001"], confidence=0.7, tech_debt_added=0),
        AgentResponse(agent_id="dev_agent_junior", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="GDPR data masking requirements unclear in HU-022 acceptance criteria.",
                      referenced_stories=["HU-022"], confidence=0.48, tech_debt_added=1),
    ],
    "qa_engineer": [
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.BLOCK_DONE,
                      rationale="HU-001 fails integration test: API Gateway returns 503 under load. Cannot mark done.",
                      referenced_stories=["HU-001"], confidence=0.95, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="All 45 test cases pass for HU-002. Coverage at 82%. Approved.",
                      referenced_stories=["HU-002"], confidence=0.9, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="No stories in IN_REVIEW state this turn. Standing by.",
                      referenced_stories=[], confidence=0.8, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Smoke tests pass. Performance within SLA bounds. Approved for staging.",
                      referenced_stories=["HU-021"], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.FLAG,
                      rationale="Missing edge case coverage for null input in HU-011 migration path.",
                      referenced_stories=["HU-011"], confidence=0.85, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Regression suite complete for HU-022. All scenarios covered. Approved.",
                      referenced_stories=["HU-022"], confidence=0.91, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.BLOCK_DONE,
                      rationale="Missing regression suite for Oracle migration path. Blocking until tests added.",
                      referenced_stories=["HU-011"], confidence=0.92, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.FLAG,
                      rationale="Performance test shows p99 latency above SLA for HU-001 under concurrent load.",
                      referenced_stories=["HU-001"], confidence=0.87, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Awaiting dev fix for known issue before resuming test cycle.",
                      referenced_stories=["HU-002"], confidence=0.78, tech_debt_added=0),
        AgentResponse(agent_id="qa_engineer", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Test environment instability affecting HU-022 results — escalating to cloud_engineer.",
                      referenced_stories=["HU-022"], confidence=0.75, tech_debt_added=0),
    ],
    "tech_lead": [
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.VETO,
                      rationale="HU-001 PR uses deprecated APIM policy syntax. Must refactor before merge.",
                      referenced_stories=["HU-001"], confidence=0.95, tech_debt_added=0),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Architecture for microservice decomposition is sound. Approved.",
                      referenced_stories=["HU-002"], confidence=0.9, tech_debt_added=0),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Oracle PL/SQL migration risk is underestimated. Needs Security Architect review.",
                      referenced_stories=["HU-011"], confidence=0.85, tech_debt_added=5),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Strangler fig pattern implementation looks correct. Good isolation boundaries.",
                      referenced_stories=["HU-021"], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="ADR-003 written: event sourcing strategy for audit trail compliance.",
                      referenced_stories=["HU-022"], confidence=0.9, artifacts=["ADR-003"], tech_debt_added=0),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="CI pipeline reviewed — security scan stage added. Merging.",
                      referenced_stories=["HU-001"], confidence=0.87, tech_debt_added=0),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.VETO,
                      rationale="Hardcoded credentials found in CI script. Cannot proceed without secret management.",
                      referenced_stories=["HU-021"], confidence=0.98, tech_debt_added=0),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Sprint velocity at risk — team needs to cut scope or accept debt. Escalating.",
                      referenced_stories=[], confidence=0.8, tech_debt_added=0),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Technical spike on Azure Service Bus throughput completed. Decision made.",
                      referenced_stories=["HU-011"], confidence=0.91, tech_debt_added=0),
        AgentResponse(agent_id="tech_lead", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Monitoring sprint progress. No blocking issues detected this turn.",
                      referenced_stories=[], confidence=0.82, tech_debt_added=0),
    ],
    "product_owner": [
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.REPRIORITIZE,
                      rationale="Business stakeholders require customer portal stories done before pipeline work.",
                      referenced_stories=["HU-001", "HU-002"], confidence=0.8, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Sprint goal alignment confirmed. All committed stories map to business value.",
                      referenced_stories=["HU-001"], confidence=0.85, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.REPRIORITIZE,
                      rationale="Compliance deadline moved up — GDPR stories must be in this sprint.",
                      referenced_stories=["HU-011", "HU-022"], confidence=0.75, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Team velocity too low for committed scope. Escalating to management.",
                      referenced_stories=["HU-001", "HU-011"], confidence=0.7, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Sprint review feedback positive. Proceeding with current backlog order.",
                      referenced_stories=[], confidence=0.82, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Acceptance criteria finalized for EPIC-02 stories with stakeholder sign-off.",
                      referenced_stories=["HU-021"], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Story HU-022 acceptance criteria met. Marking as accepted.",
                      referenced_stories=["HU-022"], confidence=0.86, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="External dependency on vendor API still unresolved — escalating to CTO.",
                      referenced_stories=["HU-002"], confidence=0.68, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="User story mapping session completed. Sprint 3 backlog refined.",
                      referenced_stories=[], confidence=0.84, tech_debt_added=0),
        AgentResponse(agent_id="product_owner", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Stakeholder demo scheduled for end of sprint. No changes to backlog.",
                      referenced_stories=[], confidence=0.79, tech_debt_added=0),
    ],
    "security_architect": [
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.FLAG,
                      rationale="APIM configuration exposes internal service endpoints. PCI-DSS violation risk.",
                      referenced_stories=["HU-001"], confidence=0.93, tech_debt_added=0),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="OAuth2 implementation reviewed. Follows GDPR data minimization principles.",
                      referenced_stories=["HU-002"], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.FLAG,
                      rationale="Oracle migration script logs sensitive PII to stdout. Must be remediated.",
                      referenced_stories=["HU-011"], confidence=0.97, tech_debt_added=8),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Key Vault integration reviewed. Secrets management meets compliance bar.",
                      referenced_stories=["HU-021"], confidence=0.91, tech_debt_added=0),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="No security-relevant changes in this turn. Monitoring.",
                      referenced_stories=[], confidence=0.85, tech_debt_added=0),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Network security group rules reviewed. Least-privilege access confirmed.",
                      referenced_stories=["HU-022"], confidence=0.89, tech_debt_added=0),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.FLAG,
                      rationale="Service-to-service auth using shared secrets instead of managed identity.",
                      referenced_stories=["HU-002"], confidence=0.94, tech_debt_added=0),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Security posture stable this sprint. Reviewing threat model documentation.",
                      referenced_stories=[], confidence=0.83, tech_debt_added=0),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Third-party library with known CVE found in HU-011 dependencies. Escalating.",
                      referenced_stories=["HU-011"], confidence=0.96, tech_debt_added=0),
        AgentResponse(agent_id="security_architect", turn=0, sprint=1, action=ActionType.VETO,
                      rationale="Proposed data retention policy violates GDPR Article 17 right to erasure.",
                      referenced_stories=["HU-021"], confidence=0.98, tech_debt_added=0),
    ],
    "cloud_engineer": [
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="AKS cluster provisioned with autoscaling. Terraform state stored in Azure Blob.",
                      referenced_stories=["HU-021"], confidence=0.87, tech_debt_added=0),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.BLOCK_DONE,
                      rationale="Azure DevOps service connection not authorized. Blocking pipeline story.",
                      referenced_stories=["HU-022"], confidence=0.9, tech_debt_added=0),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Helm chart deployed to staging namespace. Health checks passing.",
                      referenced_stories=["HU-001"], confidence=0.85, tech_debt_added=2),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="IaC reviewed. No drift detected between Terraform plan and actual resources.",
                      referenced_stories=["HU-021"], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Azure subscription quota exceeded for AKS node pools. Need approval for increase.",
                      referenced_stories=["HU-022"], confidence=0.8, tech_debt_added=0),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="CI/CD pipeline for microservice deployments configured and validated.",
                      referenced_stories=["HU-002"], confidence=0.86, tech_debt_added=0),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Container security scan results reviewed — no critical vulnerabilities.",
                      referenced_stories=["HU-011"], confidence=0.84, tech_debt_added=0),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Monitoring dashboards configured with Prometheus and Grafana. Approved.",
                      referenced_stories=["HU-001"], confidence=0.87, tech_debt_added=0),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Azure Policy compliance check blocking HU-011 deployment. Needs SA review.",
                      referenced_stories=["HU-011"], confidence=0.77, tech_debt_added=0),
        AgentResponse(agent_id="cloud_engineer", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Infrastructure stable. No deployments scheduled this turn.",
                      referenced_stories=[], confidence=0.82, tech_debt_added=0),
    ],
    "scrum_master": [
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.IMPEDIMENT,
                      rationale="Tech Lead and Product Owner in conflict over scope. Facilitating resolution.",
                      referenced_stories=[], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Team flow is healthy. No blockers detected. Velocity on track.",
                      referenced_stories=[], confidence=0.82, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.IMPEDIMENT,
                      rationale="Developer waiting 3 days for QA feedback. Raising impediment to unblock.",
                      referenced_stories=["HU-001"], confidence=0.9, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Sprint burndown shows 40% remaining with 2 days left. Escalating to management.",
                      referenced_stories=[], confidence=0.85, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.IMPEDIMENT,
                      rationale="Security review bottleneck: 5 stories waiting for security_architect sign-off.",
                      referenced_stories=["HU-011", "HU-022"], confidence=0.87, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Retrospective items being tracked. Team addressing process gaps independently.",
                      referenced_stories=[], confidence=0.8, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Sprint planning complete. Team capacity matches committed scope.",
                      referenced_stories=[], confidence=0.86, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.ESCALATE,
                      rationale="Cross-team dependency on portal team unresolved for 4 days. Escalating.",
                      referenced_stories=["HU-002"], confidence=0.83, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Daily standups show team is coordinating well. Process healthy.",
                      referenced_stories=[], confidence=0.84, tech_debt_added=0),
        AgentResponse(agent_id="scrum_master", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="No impediments raised by team. Monitoring velocity trend.",
                      referenced_stories=[], confidence=0.79, tech_debt_added=0),
    ],
    "software_architect": [
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.FLAG,
                      rationale="Microservice boundary for customer portal violates bounded context principles.",
                      referenced_stories=["HU-002"], confidence=0.88, tech_debt_added=5),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Event-driven architecture for Oracle migration aligns with long-term vision.",
                      referenced_stories=["HU-011"], confidence=0.85, tech_debt_added=0),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.VETO,
                      rationale="Proposed synchronous REST calls between microservices violates resilience ADR-001.",
                      referenced_stories=["HU-001"], confidence=0.92, tech_debt_added=0),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="ADR-002 published: async messaging via Azure Service Bus for all inter-service comms.",
                      referenced_stories=["HU-021"], confidence=0.9, artifacts=["ADR-002"], tech_debt_added=0),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="Domain model reviewed. Strangler fig decomposition follows hexagonal architecture.",
                      referenced_stories=["HU-022"], confidence=0.87, tech_debt_added=0),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.FLAG,
                      rationale="Shared database anti-pattern detected in HU-011 — services must own their schema.",
                      referenced_stories=["HU-011"], confidence=0.91, tech_debt_added=4),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.VETO,
                      rationale="Saga pattern implementation missing compensating transactions. Not production-ready.",
                      referenced_stories=["HU-002"], confidence=0.93, tech_debt_added=0),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.COMPLETE,
                      rationale="Architecture fitness function for bounded context isolation defined and documented.",
                      referenced_stories=["HU-001"], confidence=0.88, tech_debt_added=0),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.APPROVE,
                      rationale="CQRS read model design reviewed — event projections are idempotent. Approved.",
                      referenced_stories=["HU-021"], confidence=0.86, tech_debt_added=0),
        AgentResponse(agent_id="software_architect", turn=0, sprint=1, action=ActionType.IDLE,
                      rationale="Reviewing architecture decision log. No structural issues found this turn.",
                      referenced_stories=[], confidence=0.81, tech_debt_added=0),
    ],
}

_counters: dict[str, itertools.cycle] = {
    role: itertools.cycle(range(len(responses)))
    for role, responses in MOCK_RESPONSES.items()
}


class MockProvider(BaseLLMProvider):
    provider_name = "mock"

    async def complete(self, system_prompt: str, user_prompt: str) -> AgentResponse:
        # Identify role from user_prompt only (system_prompt may mention other roles as words)
        role = "developer"
        for r in MOCK_RESPONSES:
            if r in user_prompt.lower():
                role = r
                break
        idx = next(_counters[role])
        base = MOCK_RESPONSES[role][idx]
        return base.model_copy()

    def is_available(self) -> bool:
        return True
